apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: $(Release.ImageName)
  namespace: cia
spec:
  template:
    metadata:
      labels:
        alicorp.com.pe/context: cia
    spec:
      containers:
        - image: ciaalicorp.azurecr.io/$(Env.EnvPrefix)/$(Release.ImageName):$(Build.BuildNumber)
          env:
            - name: DEBUG_MODE
              value: 'false'
            - name: LOGGER_MAX_CHAR_BODY
              value: '500'
            - name: EBIZ_ENDPOINT_ACCEPTANCEHAS
              valueFrom:
                secretKeyRef:
                  name: cia-secret
                  key: EBIZ_ENDPOINT_ACCEPTANCEHAS
                  optional: false
            - name: EBIZ_ENDPOINT_ACCEPTANCEHASRETRIEVE
              valueFrom:
                secretKeyRef:
                  name: cia-secret
                  key: EBIZ_ENDPOINT_ACCEPTANCEHASRETRIEVE
                  optional: false
            - name: EBIZ_ENDPOINT_INTERNALAUTH
              valueFrom:
                secretKeyRef:
                  name: cia-secret
                  key: EBIZ_ENDPOINT_AUTH
                  optional: false
            - name: EBIZ_SUBSCRIPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: cia-secret
                  key: EBIZ_SUBSCRIPTION_KEY
                  optional: false
      imagePullSecrets:
        - name: acr-ciaalicorp
